### ISSUE TITLE
Volume issue in Reaper x64

### ISSUE THREAD

**Issue by mk-archaeo** [igorski/regrader#3]
Hi,

first of all thanks for the nice plugin.

The vst-version seems to add the volume on the Dry side. If the dry/wet fader is on the dry side both signals are there adding up to some blasting noise. If the fader is on the Wet side there is silence - no signal at all.
Maybe this helps to locate the issue.

PS: the vst3 version calls a Visual c++ runtime error

**Comment by igorski** [comment]
Dry/wet issue resolved in a previous commit, this occurred for all VST2 versions of the plugin.
VST3 version crashing on Reaper x64 resolved in https://github.com/igorski/regrader/pull/2

Code merged into master branch (website download also updated with new archive).
