### ISSUE TITLE
Problem setting sample rate

### ISSUE THREAD

**Issue by jpcima** [igorski/regrader#6]
Hello, I have done recent porting work to get this software to work as Linux LV2.

While doing the work, I noticed a problem.
The sample rate is defined as static variable in the global header.

Because of being static, compilation units which read and write `SAMPLE_RATE` are possibly going to address distinct variables.
So, assigning sample rate will not have effect on other components, and the DSP will configure itself based on default 44100 Hz.

Such behavior is verifiable of GCC and Clang compilers, about MS I don't know whether it is the case.

**Comment by igorski** [comment]
It is embarrassing that only now this problem is addressed.
This has been tackled in adb3fb81f88e6ab79e7a921324b797ba5ffe2153
