### ISSUE TITLE
[Linux] Compile error

### ISSUE THREAD

**Issue by KottV** [igorski/regrader#7]
Hi,
I'm trying to build your plugins but get this error:

```
In file included from /home/kv/src/audio/regrader/src/vstentry.cpp:24:
/home/kv/src/audio/regrader/src/ui/controller.h:41:1: error: expected class-name before ‘{’ token
   41 | {
      | ^
/home/kv/src/audio/regrader/src/ui/controller.h:77:9: error: ‘IController’ does not name a type; did you mean ‘EditController’?
   77 |         IController* createSubController( UTF8StringPtr name, const IUIDescription* description,
      |         ^~~~~~~~~~~
      |         EditController
```

does it means missing includes?

**Comment by igorski** [comment]
Hi there, _IController_ is declared by the Steinberg SDK. Did you also compile the Steinberg SDK and provide its path to cmake (using -DVST3_SDK_ROOT=/path/to/sdk) as per the [build instructions](https://github.com/igorski/regrader#build-instructions) ?

**Comment by KottV** [comment]
yes, and SDK examples are built
I can build other vst3 plugins too

I guess that is related to using VSTGUI namespace (I'm not good in c++)

**Comment by igorski** [comment]
Just for clarity: which SDK version are you using and what is your Linux distribution?

VSTGUI should be provided through the build of Steinbergs SDK, though it looks like you are already in the compilation phase (cmake would have let you know upfront if it couldn't find the required shared libraries upfront)

**Comment by KottV** [comment]
latest from git
vstsdk3612_03_12_2018_build_67-4-g0908f47
openSUSE tumbleweed gcc 9.2.1
examples from SDk and other plugins (https://github.com/ryukau/VSTPlugins for example) compiles

**Comment by igorski** [comment]
Perhaps the issue is the SDK version as Regrader was built against 3.6.9. Will investigate in a VM

**Comment by KottV** [comment]
AFAIK, 3.6.9 has broken vstgui on Linux, thus I'm not so wish to try with that old version.
Even last version has one issue for me. If you run into not found xkbcommon headers, add it's path into **vstgui4/vstgui/lib/CMakeFiles/vstgui.dir/flags.make**
after configuring with cmake (it needs a better bugfix, yes)

**Comment by igorski** [comment]
There's always something with these "minor version" changes :)

I'll have a look with 3.6.12, see if it has breaking changes for the project and take it from there.

**Comment by KottV** [comment]
If I can make some assistance - please tell)

**Comment by igorski** [comment]
Hi, I am upgrading the project to use the latest Steinberg SDK 3.6.14 and hope to tackle the Linux issues as well. Can you checkout branch 3614 and verify whether this works for you?

**Comment by KottV** [comment]
Hi!

It compiles, thanks! But refuses to load in host:

> Plugin failed to load, error was:
> Failed to get plugin description

**Comment by igorski** [comment]
Hi @KottV 

sorry for the delay :) I have created a new branch [370](https://github.com/igorski/regrader/pull/10) which uses Steinbergs latest SDK 3.7.0
I have managed to build it successfully in an Ubuntu VM where the plugin appears in the editorhost and passes the validator (both supplied by the SDK). Using Bitwig Studio as a DAW I can use the plugin (though opening the GUI has it appear black...).

Can you confirm whether the update build script is working for you as well (and maybe if you have more luck in your DAW) ?

**Comment by KottV** [comment]
It works in Carla, Reaper and JUCE-hosts!

just need to comment/remove this line:
https://github.com/igorski/regrader/blob/a74f264e0759cd8918e4d3781b005d95a8010189/CMakeLists.txt#L27

**Comment by igorski** [comment]
Thank you so much for verifying! Glad to hear the positive results!

Good thing you mentioned that line that was local to my test env, will remove it and clean up the make file further more to have less duplicate code in between the platforms prior to merging.

Thanks again for your help!

**Comment by KottV** [comment]
Many thanks to You.
Maybe other your plugins will have updates too:)
